# -*- coding: utf-8 -*-
"""brands_data.py -- single source of truth for the 18 non-flagship company skills.

Each entry carries the verified palette overrides + deck content. Shared neutral
palette roles come from DEFAULT_PAL. build_all.py turns this into palette.json,
brand.json, spec.sample.json for each skill, then renders + validates.

KPI values are ILLUSTRATIVE placeholders (labeled 예시 on the slide) -- no fabricated
real figures. Colors are cited in each entry's `src`. Trademarks belong to owners;
this is an unofficial brand-inspired theme collection.
"""

DEFAULT_PAL = {
    "font": "Pretendard",
    "ink": "1A1A1A", "sub": "4A4A4A", "muted": "8A8A8A",
    "surface": "F5F6F8", "border": "E1E3E8", "bg": "FFFFFF",
    "divider_ink": "FFFFFF",
}

# Default illustrative KPI (overridable per company)
_KPI = [["R&D·투자", "기준", "+30%", 100, 130],
        ["글로벌 매출 비중", "기준", "2.0x", 100, 200],
        ["신사업 비중", "기준", "+40%", 100, 140]]

BRANDS = {
    "samsung-mobile": {
        "label": "Samsung Galaxy", "label_ko": "삼성전자 모바일",
        "accent": "1428A0", "divider_bg": "000000",
        "tagline": "갤럭시 생태계로 모바일 경험을 혁신하는 역량",
        "owner": "삼성전자 (Samsung Electronics Co., Ltd.)",
        "src": "Samsung Blue #1428A0 (Pantone 286C), Galaxy 브랜드는 near-black 병용 — brandcolorcode.com, samsungsdi.com CI RGB(20,40,160) 일치",
        "art": "sleek premium device photography vibe, deep blue accent on near-black, minimal UI motifs, no logos",
        "font_note": "SamsungOne / Samsung Sharp Sans (사유) → Pretendard 폴백",
        "cover_title": "일상을 바꾸는\n모바일 경험", "cover_sub": "Galaxy · 스마트폰 · 웨어러블 · 갤럭시 AI",
        "div_title": "핵심 사업 영역", "div_sub": "디바이스와 AI가 만나는 모바일 생태계",
        "cells": [["갤럭시 스마트폰", "플래그십부터 보급형까지 폭넓은 라인업으로 글로벌 시장을 이끕니다."],
                  ["태블릿 · PC", "갤럭시 탭·북으로 생산성과 창작 경험을 확장합니다."],
                  ["웨어러블", "워치·버즈로 건강·오디오 경험을 손목과 귀로 넓힙니다."],
                  ["갤럭시 AI", "온디바이스 AI로 번역·요약·촬영 경험을 재정의합니다."]],
        "kpi": [["갤럭시 AI 탑재 확대", "기준", "3.0x", 100, 300],
                ["폴더블 비중", "기준", "2.0x", 100, 200],
                ["생태계 연결 기기", "기준", "+40%", 100, 140]],
        "closing_title": "모바일의 미래를\n갤럭시로 그립니다", "closing_sub": "Samsung Galaxy",
    },
    "lg-electronics": {
        "label": "LG Electronics", "label_ko": "LG전자",
        "accent": "A50034", "divider_bg": "A50034",
        "tagline": "가전·TV·전장을 아우르는 스마트 라이프 솔루션",
        "owner": "LG전자 (LG Electronics Inc.)",
        "src": "LG Red #A50034 (Heritage Red, Pantone 207C) — lgensol.com CI RGB(165,0,52) 일치, brandpalettes.com 교차확인",
        "art": "warm premium home-life imagery, LG red accent, clean minimal, no logos",
        "font_note": "Pretendard 폴백",
        "cover_title": "고객의 삶을\n더 좋게, 더 스마트하게", "cover_sub": "H&A · HE · VS · B2B Solution",
        "div_title": "핵심 사업 영역", "div_sub": "생활가전에서 전장까지 확장하는 포트폴리오",
        "cells": [["생활가전 (H&A)", "냉장고·세탁기 등 프리미엄 가전으로 글로벌 리더십을 유지합니다."],
                  ["홈엔터테인먼트 (HE)", "OLED TV를 중심으로 프리미엄 디스플레이 경험을 제공합니다."],
                  ["전장 (VS)", "차량용 인포테인먼트·전동화 부품으로 미래 모빌리티에 대응합니다."],
                  ["B2B 솔루션", "사이니지·로봇·HVAC로 상업·산업 고객 가치를 창출합니다."]],
        "kpi": [["전장 매출 비중", "기준", "2.0x", 100, 200],
                ["B2B 비중", "기준", "+45%", 100, 145],
                ["구독·서비스", "기준", "3.0x", 100, 300]],
        "closing_title": "Life's Good,\n혁신은 계속됩니다", "closing_sub": "LG Electronics",
    },
    "lg-energy": {
        "label": "LG Energy Solution", "label_ko": "LG에너지솔루션",
        "accent": "A50034", "divider_bg": "A50034",
        "tagline": "전지 전문 기업으로 여는 에너지 전환",
        "owner": "LG에너지솔루션 (LG Energy Solution Ltd.)",
        "src": "LG Red #A50034 — lgensol.com 공식 CI RGB(165,0,52)/Pantone 207C 일치",
        "art": "clean energy / battery cell imagery, LG red accent, technical precision, no logos",
        "font_note": "Pretendard 폴백",
        "cover_title": "에너지 전환을\n배터리로 이끌다", "cover_sub": "EV Battery · ESS · 소형전지 · 소재",
        "div_title": "핵심 사업 영역", "div_sub": "셀부터 소재까지 배터리 밸류체인",
        "cells": [["자동차 전지", "글로벌 완성차와 협력해 전기차 배터리 시장을 선도합니다."],
                  ["ESS", "재생에너지 저장 시스템으로 전력망 안정화에 기여합니다."],
                  ["소형전지", "IT·무선기기용 소형 셀로 다양한 응용처를 지원합니다."],
                  ["배터리 소재·순환", "핵심 소재 내재화와 리사이클로 지속가능성을 높입니다."]],
        "kpi": [["생산 캐파", "기준", "2.5x", 100, 250],
                ["북미 비중", "기준", "3.0x", 100, 300],
                ["소재 내재화", "기준", "+50%", 100, 150]],
        "closing_title": "We CHARGE\ntoward a better future", "closing_sub": "LG Energy Solution",
    },
    "samsung-sdi": {
        "label": "Samsung SDI", "label_ko": "삼성SDI",
        "accent": "1428A0", "divider_bg": "1428A0",
        "tagline": "배터리와 전자재료로 만드는 지속가능 미래",
        "owner": "삼성SDI (Samsung SDI Co., Ltd.)",
        "src": "Samsung Blue #1428A0 — samsungsdi.com/about-sdi/ci.html 공식 RGB(20,40,160)/Pantone 286C 일치",
        "art": "battery cell + advanced materials imagery, Samsung blue accent, clean tech, no logos",
        "font_note": "Pretendard 폴백",
        "cover_title": "배터리와 소재로\n미래를 충전하다", "cover_sub": "EV Battery · ESS · 소형전지 · 전자재료",
        "div_title": "핵심 사업 영역", "div_sub": "고에너지 배터리와 첨단 전자재료",
        "cells": [["자동차 전지", "고에너지 밀도 배터리로 프리미엄 전기차 시장에 대응합니다."],
                  ["ESS", "전력용·주택용 저장장치로 에너지 안정성을 지원합니다."],
                  ["소형전지", "원형·파우치 셀로 전동공구·모빌리티를 구동합니다."],
                  ["전자재료", "반도체·디스플레이 소재로 IT 산업의 기반을 제공합니다."]],
        "kpi": [["전고체 준비", "기준", "본격화", 100, 220],
                ["ESS 매출", "기준", "2.0x", 100, 200],
                ["소재 매출", "기준", "+35%", 100, 135]],
        "closing_title": "지속가능한 미래를\n함께 충전합니다", "closing_sub": "Samsung SDI",
    },
    "naver": {
        "label": "NAVER", "label_ko": "네이버",
        "accent": "03C75A", "accent_ink": "02843B", "divider_bg": "04371F",
        "tagline": "검색·커머스·핀테크·AI를 잇는 기술 플랫폼",
        "owner": "네이버 (NAVER Corp.)",
        "src": "NAVER Green #03C75A — navercorp.com 공식 브랜드가이드 HEX/RGB(3,199,90)/Pantone 2270C 직접 확인",
        "art": "clean flat tech illustration, NAVER green accent, white space, friendly geometric, no logos",
        "font_note": "Pretendard 폴백 (나눔스퀘어 계열 결)",
        "cover_title": "연결을 넘어,\n기술로 일상을 바꾸다", "cover_sub": "Search · Commerce · Fintech · AI",
        "div_title": "핵심 사업 영역", "div_sub": "검색을 축으로 확장하는 플랫폼 생태계",
        "cells": [["서치플랫폼", "검색·광고를 통해 이용자와 사업자를 연결합니다."],
                  ["커머스", "스마트스토어 생태계로 판매자의 성장을 돕습니다."],
                  ["핀테크", "네이버페이로 결제·금융 경험을 매끄럽게 만듭니다."],
                  ["콘텐츠 · 클라우드 · AI", "웹툰·클라우드·하이퍼클로바로 기술 경쟁력을 확장합니다."]],
        "kpi": [["AI 적용 서비스", "기준", "3.0x", 100, 300],
                ["글로벌 매출", "기준", "2.0x", 100, 200],
                ["커머스 거래액", "기준", "+40%", 100, 140]],
        "closing_title": "기술로 연결되는\n더 나은 일상", "closing_sub": "NAVER",
    },
    "kakao": {
        "label": "Kakao", "label_ko": "카카오",
        "accent": "FEE500", "accent_ink": "3B1E1E", "on_accent": "191919",
        "divider_bg": "FEE500", "divider_ink": "191919",
        "tagline": "관계를 잇는 플랫폼으로 만드는 일상의 혁신",
        "owner": "카카오 (Kakao Corp.)",
        "src": "Kakao Yellow #FEE500 — 카카오 디자인시스템 공식값(옐로우 배경 + 어두운 텍스트 규정), brandcolorcode.com 교차확인. 표지·섹션은 노랑 배경 + 다크 텍스트, 본문은 흰 배경",
        "art": "friendly rounded flat illustration, Kakao yellow with dark ink, warm minimal, no logos",
        "font_note": "Pretendard 폴백",
        "cover_title": "관계를 잇고,\n일상을 바꾸다", "cover_sub": "Talk · Platform · Content · AI",
        "div_title": "핵심 사업 영역", "div_sub": "카카오톡을 축으로 한 생활 플랫폼",
        "cells": [["톡비즈", "카카오톡 기반 광고·커머스로 비즈니스 연결을 돕습니다."],
                  ["플랫폼", "모빌리티·페이로 이동과 결제를 편리하게 만듭니다."],
                  ["콘텐츠", "웹툰·게임·뮤직으로 글로벌 콘텐츠 경험을 확장합니다."],
                  ["AI", "카카오 AI로 대화형 서비스와 생산성을 강화합니다."]],
        "kpi": [["AI 서비스 확대", "기준", "3.0x", 100, 300],
                ["글로벌 콘텐츠", "기준", "2.0x", 100, 200],
                ["톡비즈 매출", "기준", "+35%", 100, 135]],
        "closing_title": "연결의 힘으로\n일상을 새롭게", "closing_sub": "Kakao",
    },
    "hyundai-motor": {
        "label": "Hyundai Motor", "label_ko": "현대자동차",
        "accent": "002C5F", "divider_bg": "002C5F",
        "tagline": "내연기관을 넘어 전동화·수소·SDV로 나아가는 모빌리티",
        "owner": "현대자동차 (Hyundai Motor Company)",
        "src": "Hyundai Blue #002C5F — hyundai.com/kr CI 공식 확인, brandpalettes 교차확인",
        "art": "premium automotive imagery, Hyundai deep blue, progressive minimal, no logos",
        "font_note": "Hyundai Sans (사유) → Pretendard 폴백",
        "cover_title": "이동의 자유,\n그 이상의 진보", "cover_sub": "ICE · EV · FCEV · SDV",
        "div_title": "핵심 사업 영역", "div_sub": "전동화와 수소로 여는 미래 모빌리티",
        "cells": [["내연기관·하이브리드", "검증된 파워트레인으로 안정적 글로벌 판매를 유지합니다."],
                  ["전동화 (EV)", "전용 플랫폼 기반 전기차로 전동화 전환을 가속합니다."],
                  ["수소 (FCEV)", "수소연료전지로 상용·승용 무공해 모빌리티를 확장합니다."],
                  ["SDV · 모빌리티", "소프트웨어 중심 차량과 신모빌리티로 경험을 재정의합니다."]],
        "kpi": [["EV 판매 비중", "기준", "3.0x", 100, 300],
                ["SDV 전환", "기준", "본격화", 100, 220],
                ["수소 생태계", "기준", "+40%", 100, 140]],
        "closing_title": "Progress\nfor Humanity", "closing_sub": "Hyundai Motor",
    },
    "kia": {
        "label": "Kia", "label_ko": "기아",
        "accent": "EA0029", "divider_bg": "05141F",
        "tagline": "지속가능한 모빌리티 솔루션 프로바이더",
        "owner": "기아 (Kia Corporation)",
        "src": "Kia Live Red #EA0029 + Midnight Black #05141F — 2021 리브랜드 공식 CI 가이드",
        "art": "bold modern automotive imagery, Kia red on midnight black, dynamic minimal, no logos",
        "font_note": "Kia Signature (사유) → Pretendard 폴백",
        "cover_title": "영감을 주는\n움직임", "cover_sub": "EV · SUV · PBV · Mobility",
        "div_title": "핵심 사업 영역", "div_sub": "전동화와 목적기반차량으로의 전환",
        "cells": [["EV 라인업", "전용 전기차 라인업으로 대중 전동화를 이끕니다."],
                  ["SUV", "글로벌 인기 SUV로 브랜드 판매의 중심을 담당합니다."],
                  ["PBV", "목적기반차량으로 물류·모빌리티 신시장을 개척합니다."],
                  ["모빌리티 솔루션", "구독·카헤일링 등 서비스로 이동 경험을 확장합니다."]],
        "kpi": [["EV 비중", "기준", "3.0x", 100, 300],
                ["PBV 신사업", "기준", "본격화", 100, 220],
                ["브랜드 선호", "기준", "+35%", 100, 135]],
        "closing_title": "Movement\nthat inspires", "closing_sub": "Kia",
    },
    "posco": {
        "label": "POSCO", "label_ko": "포스코",
        "accent": "053080", "secondary": "00A5E5", "divider_bg": "053080",
        "tagline": "철강을 넘어 2차전지 소재로 확장하는 소재 기업",
        "owner": "포스코 (POSCO Holdings)",
        "src": "POSCO Blue #053080 + Light Blue #00A5E5 — posco.com 공식 CI, brandcolorcode 교차확인",
        "art": "industrial steel + battery-materials imagery, POSCO blue, strong geometric, no logos",
        "font_note": "Pretendard 폴백",
        "cover_title": "소재로 미래를\n짓다", "cover_sub": "Steel · Battery Materials · Lithium · Green",
        "div_title": "핵심 사업 영역", "div_sub": "철강과 2차전지 소재의 균형 성장",
        "cells": [["철강", "친환경 고급강으로 글로벌 철강 리더십을 이어갑니다."],
                  ["2차전지 소재", "양·음극재로 배터리 밸류체인의 핵심을 담당합니다."],
                  ["리튬 · 니켈", "원료 확보로 소재 사업의 수직계열화를 완성합니다."],
                  ["친환경", "수소·저탄소 공정으로 탄소중립 전환을 추진합니다."]],
        "kpi": [["2차전지 소재 매출", "기준", "3.0x", 100, 300],
                ["저탄소 공정", "기준", "본격화", 100, 220],
                ["리튬 자급", "기준", "+50%", 100, 150]],
        "closing_title": "더 나은 미래를\n소재로 만듭니다", "closing_sub": "POSCO",
    },
    "hd-hyundai": {
        "label": "HD Hyundai", "label_ko": "HD현대",
        "accent": "00AD1D", "secondary": "003087", "divider_bg": "003087",
        "tagline": "조선·에너지·기계를 아우르는 중공업 리더",
        "owner": "HD현대 (HD Hyundai Co., Ltd.)",
        "src": "HD Heritage Green #00AD1D / Discovery Blue #003087 — 2023 리브랜드 (unverified 추정, 다음뉴스 리브랜드 보도 참고)",
        "art": "heavy-industry / shipyard imagery, HD green-blue accents, robust minimal, no logos",
        "font_note": "Pretendard 폴백",
        "cover_title": "바다에서 미래로,\n중공업의 진화", "cover_sub": "Shipbuilding · Machinery · Energy · Robotics",
        "div_title": "핵심 사업 영역", "div_sub": "조선·에너지·기계·로봇의 통합 역량",
        "cells": [["조선 · 해양", "친환경 선박과 해양플랜트로 글로벌 수주를 이끕니다."],
                  ["건설기계", "굴착기 등 기계로 세계 인프라 건설에 기여합니다."],
                  ["에너지", "정유·전동화 솔루션으로 에너지 전환에 대응합니다."],
                  ["로보틱스", "산업·서비스 로봇으로 미래 성장 동력을 확보합니다."]],
        "kpi": [["친환경 선박 수주", "기준", "2.5x", 100, 250],
                ["로보틱스 매출", "기준", "3.0x", 100, 300],
                ["에너지 전환", "기준", "+40%", 100, 140]],
        "closing_title": "미래를 여는\n중공업의 힘", "closing_sub": "HD Hyundai",
    },
    "doosan": {
        "label": "Doosan", "label_ko": "두산",
        "accent": "0017A8", "secondary": "0087CE", "divider_bg": "0017A8",
        "tagline": "에너지·기계·첨단산업을 잇는 인프라 지원 기업",
        "owner": "두산 (Doosan Corporation)",
        "src": "Doosan Blue #0017A8 + Process Blue #0087CE — doosan.com 공식 CI 가이드라인",
        "art": "energy + machinery imagery, Doosan blue, engineering precision, no logos",
        "font_note": "Pretendard 폴백",
        "cover_title": "내일을 움직이는\n힘", "cover_sub": "Energy · Machinery · Semiconductor · Robotics",
        "div_title": "핵심 사업 영역", "div_sub": "에너지와 첨단 산업의 성장 축",
        "cells": [["에너지", "발전 설비와 SMR·수소로 미래 에너지에 대응합니다."],
                  ["건설기계", "글로벌 건설기계 라인업으로 인프라를 지원합니다."],
                  ["반도체", "테스나 등 후공정 역량으로 반도체 밸류체인에 참여합니다."],
                  ["로보틱스", "협동로봇으로 제조 자동화 시장을 확대합니다."]],
        "kpi": [["SMR·수소", "기준", "본격화", 100, 220],
                ["반도체 매출", "기준", "2.0x", 100, 200],
                ["협동로봇", "기준", "3.0x", 100, 300]],
        "closing_title": "내일을 위한\n오늘의 기술", "closing_sub": "Doosan",
    },
    "hanwha": {
        "label": "Hanwha", "label_ko": "한화",
        "accent": "F37321", "accent_ink": "B8560F", "divider_bg": "1B1B1B",
        "tagline": "방산·에너지·금융·우주를 잇는 미래 산업 그룹",
        "owner": "한화 (Hanwha Group)",
        "src": "Hanwha Orange #F37321 — hanwha.com 브랜드 시스템 가이드, brandcolorcode 교차확인",
        "art": "aerospace / clean-energy imagery, Hanwha orange accent on dark, bold minimal, no logos",
        "font_note": "Pretendard 폴백",
        "cover_title": "지속가능한 미래를\n설계하다", "cover_sub": "Defense · Energy · Finance · Space",
        "div_title": "핵심 사업 영역", "div_sub": "방산부터 우주까지 확장하는 포트폴리오",
        "cells": [["방산", "지상·해양 방산 체계로 국가 안보에 기여합니다."],
                  ["에너지", "태양광 밸류체인으로 친환경 에너지를 확대합니다."],
                  ["금융", "보험·자산운용으로 종합 금융 서비스를 제공합니다."],
                  ["우주 (스페이스)", "발사체·위성으로 우주 산업의 미래에 도전합니다."]],
        "kpi": [["방산 수출", "기준", "2.5x", 100, 250],
                ["태양광 캐파", "기준", "+45%", 100, 145],
                ["우주 사업", "기준", "본격화", 100, 220]],
        "closing_title": "미래를 향한\n담대한 도전", "closing_sub": "Hanwha",
    },
    "nongshim": {
        "label": "Nongshim", "label_ko": "농심",
        "accent": "DF0029", "secondary": "EC870C", "divider_bg": "DF0029",
        "tagline": "라면과 스낵으로 세계인의 입맛을 사로잡는 식품 기업",
        "owner": "농심 (Nongshim Co., Ltd.)",
        "src": "Nongshim Red #DF0029 + Orange #EC870C — eng.nongshim.com/about/ci 공식 직접 확인 (흰 텍스트 대비 5:1 AA)",
        "art": "appetizing food imagery, Nongshim red accent, warm inviting, no logos",
        "font_note": "Pretendard 폴백",
        "cover_title": "세계인이 즐기는\n대한민국의 맛", "cover_sub": "Ramyun · Snack · Beverage · Global",
        "div_title": "핵심 사업 영역", "div_sub": "국내 1위를 넘어 글로벌 식품 기업으로",
        "cells": [["라면", "신라면을 앞세워 국내외 라면 시장을 선도합니다."],
                  ["스낵", "새우깡 등 스테디셀러로 스낵 시장을 이끕니다."],
                  ["음료 · 생수", "백산수 등으로 음료·생수 포트폴리오를 확장합니다."],
                  ["글로벌", "미국·중국 생산기지로 K-푸드 세계화를 가속합니다."]],
        "kpi": [["글로벌 매출 비중", "기준", "2.0x", 100, 200],
                ["미주 매출", "기준", "3.0x", 100, 300],
                ["신제품 비중", "기준", "+35%", 100, 135]],
        "closing_title": "맛있는 라면을 넘어\n세계인의 식탁으로", "closing_sub": "Nongshim",
    },
    "sk-telecom": {
        "label": "SK Telecom", "label_ko": "SK텔레콤",
        "accent": "EA002C", "divider_bg": "A8001F",
        "tagline": "통신을 넘어 AI 컴퍼니로 전환하는 리더",
        "owner": "SK텔레콤 (SK Telecom Co., Ltd.)",
        "src": "SK Red #EA002C (SK그룹 공통 CI, SKT 로고 적용) — sk.co.kr CI. divider는 대비 안전 위해 어둡게 조정(#A8001F)",
        "art": "connectivity + AI imagery, SK red accent, sleek futuristic, no logos",
        "font_note": "Pretendard 폴백",
        "cover_title": "통신을 넘어,\nAI 컴퍼니로", "cover_sub": "Connectivity · AI · Cloud · Media",
        "div_title": "핵심 사업 영역", "div_sub": "통신 기반 위에 AI를 얹다",
        "cells": [["유무선 통신", "5G 네트워크로 국내 통신 시장의 리더십을 유지합니다."],
                  ["AI (에이닷)", "AI 개인비서와 AIDC로 AI 서비스를 확장합니다."],
                  ["데이터센터 · 클라우드", "AI 데이터센터·클라우드로 인프라 사업을 키웁니다."],
                  ["미디어", "IPTV·콘텐츠로 미디어 경험을 넓힙니다."]],
        "kpi": [["AI 매출 비중", "기준", "3.0x", 100, 300],
                ["AIDC 캐파", "기준", "2.5x", 100, 250],
                ["구독 서비스", "기준", "+40%", 100, 140]],
        "closing_title": "AI로 연결되는\n새로운 일상", "closing_sub": "SK Telecom",
    },
    "celltrion": {
        "label": "Celltrion", "label_ko": "셀트리온",
        "accent": "50B848", "accent_ink": "2E7D32", "secondary": "000000", "divider_bg": "00552D",
        "tagline": "바이오시밀러와 신약으로 여는 글로벌 헬스케어",
        "owner": "셀트리온 (Celltrion, Inc.)",
        "src": "Celltrion Green 시스템 — celltrion.com 공식 6단계 그린(#96F0A5~#00552D). accent #50B848(근접 추정), 최암색 #00552D divider(대비 9:1). ⚠️ 블루 아님",
        "art": "clean biotech / life-science imagery, Celltrion green, precise clinical, no logos",
        "font_note": "Pretendard 폴백",
        "cover_title": "생명을 위한\n바이오 혁신", "cover_sub": "Biosimilar · Novel Drug · Chemical · Global",
        "div_title": "핵심 사업 영역", "div_sub": "바이오시밀러를 넘어 신약으로",
        "cells": [["바이오시밀러", "항체 바이오시밀러로 글로벌 시장 접근성을 넓힙니다."],
                  ["신약 개발", "신규 파이프라인으로 미래 성장 동력을 확보합니다."],
                  ["케미컬", "제네릭·개량신약으로 사업 포트폴리오를 다각화합니다."],
                  ["글로벌 헬스케어", "직판 체계로 세계 환자에게 직접 다가갑니다."]],
        "kpi": [["파이프라인 확대", "기준", "2.0x", 100, 200],
                ["직판 비중", "기준", "3.0x", 100, 300],
                ["신약 비중", "기준", "본격화", 100, 220]],
        "closing_title": "건강한 미래를\n함께 만듭니다", "closing_sub": "Celltrion",
    },
    "kb-financial": {
        "label": "KB Financial Group", "label_ko": "KB금융그룹",
        "accent": "FFBC00", "accent_ink": "8A6A00", "on_accent": "2B2B2B", "divider_bg": "2B2B2B",
        "tagline": "은행·증권·보험을 아우르는 종합 금융 그룹",
        "owner": "KB금융그룹 (KB Financial Group Inc.)",
        "src": "KB Yellow #FFBC00 (대표컬러, 정확 hex는 공식 다운로드 자산에만 — 추정) — kbfg.com CI. 옐로우 divider 금지 → 차콜 #2B2B2B 사용",
        "art": "trustworthy finance imagery, KB yellow accent with dark ink, warm professional, no logos",
        "font_note": "Pretendard 폴백",
        "cover_title": "고객의 내일을\n함께 그리다", "cover_sub": "Bank · Securities · Insurance · Digital",
        "div_title": "핵심 사업 영역", "div_sub": "은행을 축으로 한 종합 금융 포트폴리오",
        "cells": [["은행", "KB국민은행을 중심으로 리테일 금융을 선도합니다."],
                  ["증권", "자본시장 서비스로 자산관리·IB를 제공합니다."],
                  ["보험", "생명·손해보험으로 생애주기 보장을 지원합니다."],
                  ["디지털 · 글로벌", "디지털 전환과 해외 진출로 미래 성장을 준비합니다."]],
        "kpi": [["비은행 이익 비중", "기준", "+40%", 100, 140],
                ["디지털 고객", "기준", "2.0x", 100, 200],
                ["글로벌 이익", "기준", "2.5x", 100, 250]],
        "closing_title": "고객의 내일에\n가치를 더합니다", "closing_sub": "KB Financial Group",
    },
    "shinhan": {
        "label": "Shinhan Financial Group", "label_ko": "신한금융그룹",
        "accent": "0046FF", "divider_bg": "0046FF",
        "tagline": "은행·카드·증권을 잇는 리딩 금융 그룹",
        "owner": "신한금융그룹 (Shinhan Financial Group)",
        "src": "Shinhan Blue #0046FF — shinhanci.co.kr CI + color-hex 교차확인 (흰 텍스트 대비 6.3:1)",
        "art": "modern finance imagery, Shinhan blue accent, confident minimal, no logos",
        "font_note": "Pretendard 폴백",
        "cover_title": "더 나은 내일을\n금융으로", "cover_sub": "Bank · Card · Securities · Life",
        "div_title": "핵심 사업 영역", "div_sub": "은행을 축으로 한 균형 잡힌 포트폴리오",
        "cells": [["은행", "신한은행을 중심으로 리테일·기업 금융을 이끕니다."],
                  ["카드", "신한카드로 결제·소비 데이터 경쟁력을 확보합니다."],
                  ["투자증권", "자본시장 서비스로 자산관리와 IB를 제공합니다."],
                  ["라이프 · 디지털", "보험과 디지털 플랫폼으로 성장 축을 넓힙니다."]],
        "kpi": [["비은행 비중", "기준", "+40%", 100, 140],
                ["디지털 고객", "기준", "2.0x", 100, 200],
                ["글로벌 이익", "기준", "2.5x", 100, 250]],
        "closing_title": "고객과 함께\n미래를 열다", "closing_sub": "Shinhan Financial Group",
    },
    "cj-cheiljedang": {
        "label": "CJ CheilJedang", "label_ko": "CJ제일제당",
        "accent": "EF151E", "secondary": "006ECD", "divider_bg": "A30F16",
        "tagline": "식품과 바이오로 K-푸드를 세계에 알리는 기업",
        "owner": "CJ제일제당 (CJ CheilJedang Corp.)",
        "src": "CJ Blossom Red #EF151E (계열 CJ Logistics 공식 추출값, CJ그룹 Blossom 3색과 일치 — CJ제일제당 전용 PDF 추출 실패로 추정). divider는 어둡게(#A30F16)",
        "art": "appetizing K-food imagery, CJ red accent, vibrant appetizing, no logos",
        "font_note": "Pretendard 폴백",
        "cover_title": "K-푸드를\n세계의 식탁으로", "cover_sub": "Food · Bio · Feed&Care · Global",
        "div_title": "핵심 사업 영역", "div_sub": "식품과 바이오의 두 성장 축",
        "cells": [["식품", "비비고 등 글로벌 브랜드로 K-푸드를 확산합니다."],
                  ["바이오", "아미노산 등 그린바이오로 세계 시장을 선도합니다."],
                  ["Feed&Care", "사료·축산 사업으로 글로벌 식량 밸류체인에 참여합니다."],
                  ["글로벌", "북미·유럽 생산기지로 해외 매출을 확대합니다."]],
        "kpi": [["글로벌 식품 매출", "기준", "2.0x", 100, 200],
                ["바이오 매출", "기준", "+45%", 100, 145],
                ["비비고 브랜드", "기준", "3.0x", 100, 300]],
        "closing_title": "K-푸드로\n세계를 잇습니다", "closing_sub": "CJ CheilJedang",
    },
}
